### ISSUE TITLE
Error getting car info

### ISSUE THREAD

**Issue by cizetta** [HomeACcessoryKid/Domoticz-Renault-Plugin#1]
Hello, 

I'm trying to get the information of my Renault via the plugin. 
Installation and configuration seems fine but I get this error in the log:

```
2024-08-30 21:43:26.191 Status: Renault: Entering work loop.
2024-08-30 21:43:26.191 Renault: Worker thread started.
2024-08-30 21:43:26.191 Status: Renault: Started.
2024-08-30 21:43:28.117 Status: Renault: Initialized version 0.2.8, author 'HomeACcessoryKid'
2024-08-30 21:43:30.132 Status: Renault: Using accountID: 2a33e691-6a9e-4bec-8ba4-2f1cb19f40ba
2024-08-30 21:43:30.132 Renault: Succesfully logged on
2024-08-30 21:43:30.447 Status: Renault: Using VIN: VF1RHN00773229957 LicensePlate: Model: AUSTRAL HEV
2024-08-30 21:43:30.459 Renault: Engaging Vehicle
2024-08-30 21:43:31.607 Error: Renault: Retrieve Error: ('err.func.wired.forbidden', 'The access is forbidden')
2024-08-30 21:43:31.613 Error: Renault: Vehicle status could not be retrieved
```

Sharing all data with My Renault is enabled on the car.
I can see the info in MyRenault app on my phone.

Could you please guide me what should I check/configure additonally?

Thank you in advance!

**Comment by erwinjong** [comment]
same error here. just started using this plugin this week but getting the same error:

Retrieve Error: ('err.func.wired.forbidden', 'The access is forbidden')

**Comment by HomeACcessoryKid** [comment]
It is working for me as can be seen below.

I do not know which type of contract you have, but let's first check you configured the right locale = country
Also, it is suspicious your Licence Plate is not reported, mine is

Note that this is based on the https://github.com/hacf-fr/renault-api module, so you might test that standalone.
At least report the version you use with: `pip show renault-api`. Mine is 0.2.0
If that does not work, then put full debug and report

PS. obscure your accountID, VIN, licence plate AND GPS location for better privacy!

```
2024-08-31 12:25:38.934 Captur: Succesfully logged on
2024-08-31 12:25:38.010 Status: Captur: Initialized version 0.2.8, author 'HomeACcessoryKid'
2024-08-31 12:25:38.934 Status: Captur: Using accountID: dexxxxxxxxxxx8e
2024-08-31 12:25:39.222 Captur: Engaging Vehicle
2024-08-31 12:25:39.216 Status: Captur: Using VIN: VFxxxxxxxx1 LicensePlate: XXXXXX Model: CAPTUR II PHEV
2024-08-31 12:25:40.959 Captur: [KamereonVehicleCockpitData(raw_data={'fuelAutonomy': 477, 'fuelQuantity': 23.0, 'totalMileage': 4xx7}, fuelAutonomy=477.0, fuelQuantity=23.0, totalMileage=4xx7.0), KamereonVehicleChargeModeData(raw_data={'chargeMode': 'schedule_mode'}, chargeMode='schedule_mode'), KamereonVehicleBatteryStatusData(raw_data={'timestamp': '2024-08-31T09:01:26Z', 'batteryLevel': 100, 'batteryAutonomy': 50, 'plugStatus': 1, 'chargingStatus': 0.2, 'chargingRemainingTime': 20}, timestamp='2024-08-31T09:01:26Z', batteryLevel=100, batteryTemperature=None, batteryAutonomy=50, batteryCapacity=None, batteryAvailableEnergy=None, plugStatus=1, chargingStatus=0.2, chargingRemainingTime=20, chargingInstantaneousPower=None), KamereonVehicleLocationData(raw_data={'lastUpdateTime': '2024-05-14T19:23:34Z', 'gpsLatitude': xx.08638055555556, 'gpsLongitude': xx.012063055555555}, lastUpdateTime='2024-05-14T19:23:34Z', gpsLatitude=xx.08638055555556, gpsLongitude=xx.012063055555555), KamereonVehicleHvacStatusData(raw_data={'internalTemperature': 22.0, 'hvacStatus': 'off', 'lastUpdateTime': '2024-08-31T09:03:52Z'}, lastUpdateTime='2024-08-31T09:03:52Z', externalTemperature=None, hvacStatus='off', nextHvacStartDate=None, socThreshold=None)]
2024-08-31 12:25:41.054 Status: Captur: Action.NO_ACTION
```

**Comment by cizetta** [comment]
Hello,

It seems to be with the renault-api versions. 
This is with ver. 0.2.0:

```
root@rasptest:/home/gd#` renault-api --version
renault-api, version 0.2.0
root@rasptest:/home/gd# renault-api --log status
    ID                                    Type         Vehicles
--  ------------------------------------  ---------  ----------
 1  ******								 MYRENAULT           1

Please select account [1]: 1
Do you want to save the account ID to the credential store? [y/N]: 

    Vin                Registration    Brand    Model
--  -----------------  --------------  -------  -------
 1  ********		                   RENAULT  AUSTRAL

Please select vehicle [1]: 1
Do you want to save the VIN to the credential store? [y/N]: 

Traceback (most recent call last):
  File "/usr/local/bin/renault-api", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/renault_api/cli/helpers.py", line 39, in wrapper
    asyncio.run(run_command(func, *args, **kwargs))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/renault_api/cli/helpers.py", line 30, in run_command
    await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/renault_api/cli/__main__.py", line 178, in status
    await renault_vehicle.display_status(websession, ctx_data)
  File "/usr/local/lib/python3.9/dist-packages/renault_api/cli/renault_vehicle.py", line 159, in display_status
    await update_cockpit(vehicle, status_table, ctx_data)
  File "/usr/local/lib/python3.9/dist-packages/renault_api/cli/renault_vehicle.py", line 267, in update_cockpit
    ("Total mileage", response.totalMileage, "km"),
AttributeError: 'NoneType' object has no attribute 'totalMileage'
```
This is with the latest version 0.2.7:

```
root@rasptest:/home/gd# renault-api --version
renault-api, version 0.2.7
root@rasptest:/home/gd# renault-api --log status
    ID                                    Type         Vehicles
--  ------------------------------------  ---------  ----------
 1  ****								  MYRENAULT           1

Please select account [1]: 1
Do you want to save the account ID to the credential store? [y/N]: 

    Vin                Registration    Brand    Model
--  -----------------  --------------  -------  -------
 1  ****			                   RENAULT  AUSTRAL

Please select vehicle [1]: 1
Do you want to save the VIN to the credential store? [y/N]: 

lock status: {"errors":[{"errorCode":404,"errorMessage":"There is no data for this vin and uid","errorLevel":"error","errorType":"functional"}],"error_reference":"rrt-075243afd38caf90d-a-eu-22767-12034326-759"}
res state: The access is forbidden
hvac-status: {"errors":[{"errorCode":404,"errorMessage":"There is no data for this vin and uid","errorLevel":"error","errorType":"functional"}],"error_reference":"rrt-03d931990128a31d5-b-eu-22386-11002247-58"}
----------------  -------------------
Total mileage     1763.0 km
Fuel autonomy     919.0 km
Fuel quantity     48.0 L
GPS Latitude      42.6643575
GPS Longitude     23.3811875
```

Tested also with v.2.2.2 - info is also displayed.

**Comment by HomeACcessoryKid** [comment]
So, if you use v0.2.7 with my script, does it fix your problem? And did you put locale to bulgaria?
It is possible I have locally updated the renault-api manually without using pip, but we'll check that after you checked the above...

**Comment by cizetta** [comment]
Yes, I've set Bulgaria (I'm located there). It seems not to work with api v2.2.7 (Renault is the name of the Hardware I've set). 

```
2024-09-01 18:20:41.741 Error: Renault: Call to function 'onStart' failed, exception details:
2024-09-01 18:20:41.802 Error: Renault: Traceback (most recent call last):
2024-09-01 18:20:41.803 Error: Renault: File "/usr/local/lib/python3.9/dist-packages/aiohttp/connector.py", line 1301, in _create_direct_connection
2024-09-01 18:20:41.803 Error: Renault: hosts = await self._resolve_host(host, port, traces=traces)
2024-09-01 18:20:41.803 Error: Renault: File "/usr/local/lib/python3.9/dist-packages/aiohttp/connector.py", line 911, in _resolve_host
2024-09-01 18:20:41.803 Error: Renault: return await asyncio.shield(resolved_host_task)
2024-09-01 18:20:41.803 Error: Renault: File "/usr/local/lib/python3.9/dist-packages/aiohttp/connector.py", line 948, in _resolve_host_with_throttle
2024-09-01 18:20:41.803 Error: Renault: addrs = await self._resolver.resolve(host, port, family=self._family)
2024-09-01 18:20:41.804 Error: Renault: File "/usr/local/lib/python3.9/dist-packages/aiohttp/resolver.py", line 37, in resolve
2024-09-01 18:20:41.804 Error: Renault: infos = await self._loop.getaddrinfo(
2024-09-01 18:20:41.804 Error: Renault: File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
2024-09-01 18:20:41.804 Error: Renault: return await self.run_in_executor(
2024-09-01 18:20:41.804 Error: Renault: File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
2024-09-01 18:20:41.804 Error: Renault: result = self.fn(*self.args, **self.kwargs)
2024-09-01 18:20:41.804 Error: Renault: File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
2024-09-01 18:20:41.804 Error: Renault: for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2024-09-01 18:20:41.804 Error: Renault: socket.gaierror: [Errno -3] Temporary failure in name resolution
2024-09-01 18:20:41.805 Error: Renault:
2024-09-01 18:20:41.805 Error: Renault: The above exception was the direct cause of the following exception:
2024-09-01 18:20:41.805 Error: Renault:
2024-09-01 18:20:41.805 Error: Renault: Traceback (most recent call last):
2024-09-01 18:20:41.805 Error: Renault: File "/home/gd/domoticz/plugins/Domoticz-Renault-Plugin/plugin.py", line 809, in onStart
2024-09-01 18:20:41.805 Error: Renault: _plugin.update_devices()
2024-09-01 18:20:41.805 Error: Renault: File "/home/gd/domoticz/plugins/Domoticz-Renault-Plugin/plugin.py", line 768, in update_devices
2024-09-01 18:20:41.805 Error: Renault: vehicle_status = self.engage_vehicle(next_action)
2024-09-01 18:20:41.805 Error: Renault: File "/home/gd/domoticz/plugins/Domoticz-Renault-Plugin/plugin.py", line 356, in engage_vehicle
2024-09-01 18:20:41.806 Error: Renault: asyncio.run(self._connect_to_myr())
2024-09-01 18:20:41.806 Error: Renault: File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
2024-09-01 18:20:41.806 Error: Renault: return loop.run_until_complete(main)
2024-09-01 18:20:41.806 Error: Renault: File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
2024-09-01 18:20:41.806 Error: Renault: return future.result()
2024-09-01 18:20:41.806 Error: Renault: File "/home/gd/domoticz/plugins/Domoticz-Renault-Plugin/plugin.py", line 239, in _connect_to_myr
2024-09-01 18:20:41.806 Error: Renault: await client.session.login(Parameters['Username'], Parameters['Password'])
2024-09-01 18:20:41.806 Error: Renault: File "/usr/local/lib/python3.9/dist-packages/renault_api/renault_session.py", line 59, in login
2024-09-01 18:20:41.806 Error: Renault: response = await gigya.login(
2024-09-01 18:20:41.807 Error: Renault: File "/usr/local/lib/python3.9/dist-packages/renault_api/gigya/__init__.py", line 57, in login
2024-09-01 18:20:41.807 Error: Renault: await request(
2024-09-01 18:20:41.807 Error: Renault: File "/usr/local/lib/python3.9/dist-packages/renault_api/gigya/__init__.py", line 32, in request
2024-09-01 18:20:41.807 Error: Renault: async with websession.request(method, url, data=data) as http_response:
2024-09-01 18:20:41.807 Error: Renault: File "/usr/local/lib/python3.9/dist-packages/aiohttp/client.py", line 1353, in __aenter__
2024-09-01 18:20:41.807 Error: Renault: self._resp = await self._coro
2024-09-01 18:20:41.807 Error: Renault: File "/usr/local/lib/python3.9/dist-packages/aiohttp/client.py", line 657, in _request
2024-09-01 18:20:41.807 Error: Renault: conn = await self._connector.connect(
2024-09-01 18:20:41.807 Error: Renault: File "/usr/local/lib/python3.9/dist-packages/aiohttp/connector.py", line 564, in connect
2024-09-01 18:20:41.808 Error: Renault: proto = await self._create_connection(req, traces, timeout)
2024-09-01 18:20:41.808 Error: Renault: File "/usr/local/lib/python3.9/dist-packages/aiohttp/connector.py", line 975, in _create_connection
2024-09-01 18:20:41.808 Error: Renault: _, proto = await self._create_direct_connection(req, traces, timeout)
2024-09-01 18:20:41.808 Error: Renault: File "/usr/local/lib/python3.9/dist-packages/aiohttp/connector.py", line 1307, in _create_direct_connection
2024-09-01 18:20:41.808 Error: Renault: raise ClientConnectorError(req.connection_key, exc) from exc
2024-09-01 18:20:41.808 Error: Renault: aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host accounts.eu1.gigya.com:443 ssl:default [Temporary failure in name resolution]
```

**Comment by HomeACcessoryKid** [comment]
if your DNS does not resolve that hostname, there is little I can do
Maybe a temporary outage on your provider...
My view:
;accounts.eu1.gigya.com.		IN	A

;; ANSWER SECTION:
accounts.eu1.gigya.com.	862	IN	CNAME	farm5.eu1.gigya.com.
farm5.eu1.gigya.com.	862	IN	CNAME	lb.eu1.gigya.com.
lb.eu1.gigya.com.	23	IN	A	54.229.120.124

**Comment by cizetta** [comment]
I can totally dig the domain.

```
# dig accounts.eu1.gigya.com

; <<>> DiG 9.16.37-Raspbian <<>> accounts.eu1.gigya.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2518
;; flags: qr rd ra; QUERY: 1, ANSWER: 10, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;accounts.eu1.gigya.com.		IN	A

;; ANSWER SECTION:
accounts.eu1.gigya.com.	900	IN	CNAME	farm5.eu1.gigya.com.
farm5.eu1.gigya.com.	900	IN	CNAME	lb.eu1.gigya.com.
lb.eu1.gigya.com.	30	IN	A	52.19.57.181
lb.eu1.gigya.com.	30	IN	A	52.30.9.119
lb.eu1.gigya.com.	30	IN	A	52.31.157.92
lb.eu1.gigya.com.	30	IN	A	52.49.16.186
lb.eu1.gigya.com.	30	IN	A	52.212.156.205
lb.eu1.gigya.com.	30	IN	A	54.229.120.124
lb.eu1.gigya.com.	30	IN	A	52.17.82.217
lb.eu1.gigya.com.	30	IN	A	52.17.121.244

;; Query time: 39 msec
;; SERVER: 192.168.1.100#53(192.168.1.100)
;; WHEN: Mon Sep 02 00:42:53 EEST 2024
;; MSG SIZE  rcvd: 216

```

**Comment by HomeACcessoryKid** [comment]
If your domoticz log output reports it cannot resolve names then that is a fundamental issue you need to solve.
I wonder if you need to use Python 3.10 and/or Domoticz 2024.4 or higher...
And finally, please run the plugin with full debugging and report the ENTIRE log after start...
It will be a lot, but else no-one can help properly

**Comment by cizetta** [comment]
Hello,

This is the Domoticz configuration:

```
Version: 2024.7 (build 16200)
Build Hash: 7bc328c76
Compile Date: 2024-08-27 09:04:55
Python Version: 3.9.2 (default, Mar 12 2021, 04:06:34) [GCC 10.2.1 20210110]
```

And log with debung on


```
2024-09-02 14:27:37.850 Status: Renault: Entering work loop.
2024-09-02 14:27:37.850 Renault: Worker thread started.
2024-09-02 14:27:37.850 Status: Renault: Started.
2024-09-02 14:27:39.649 Status: Renault: Initialized version 0.2.8, author 'HomeACcessoryKid'
2024-09-02 14:27:39.654 Renault: Debug logging mask set to: PYTHON PLUGIN QUEUE IMAGE DEVICE CONNECTION MESSAGE
2024-09-02 14:27:39.655 Renault: 'HardwareID': '16'
2024-09-02 14:27:39.655 Renault: 'HomeFolder': '/home/gd/domoticz/plugins/Domoticz-Renault-Plugin/'
2024-09-02 14:27:39.655 Renault: 'StartupFolder': '/home/gd/domoticz/'
2024-09-02 14:27:39.655 Renault: 'UserDataFolder': '/home/gd/domoticz/'
2024-09-02 14:27:39.655 Renault: 'Database': '/home/gd/domoticz/domoticz.db'
2024-09-02 14:27:39.655 Renault: 'Language': 'en'
2024-09-02 14:27:39.655 Renault: 'Version': '0.2.8'
2024-09-02 14:27:39.655 Renault: 'Author': 'HomeACcessoryKid'
2024-09-02 14:27:39.655 Renault: 'Name': 'Renault'
2024-09-02 14:27:39.655 Renault: 'Port': '0'
2024-09-02 14:27:39.655 Renault: 'Username': '******'
2024-09-02 14:27:39.655 Renault: 'Password': '******'
2024-09-02 14:27:39.655 Renault: 'Key': 'Renault'
2024-09-02 14:27:39.655 Renault: 'Mode2': 'bg_BG'
2024-09-02 14:27:39.655 Renault: 'Mode6': '-1'
2024-09-02 14:27:39.655 Renault: 'DomoticzVersion': '2024.7 (build 16200)'
2024-09-02 14:27:39.655 Renault: 'DomoticzHash': '7bc328c76'
2024-09-02 14:27:39.655 Renault: 'DomoticzBuildTime': '2024-08-27 09:04:55'
2024-09-02 14:27:39.655 Renault: Device count: 8
2024-09-02 14:27:39.655 Renault: Device: 1 - ID: 210, Name: 'Renault - Distance', nValue: 0, sValue: ''
2024-09-02 14:27:39.655 Renault: Device ID: '210'
2024-09-02 14:27:39.655 Renault: Device Name: 'Renault - Distance'
2024-09-02 14:27:39.655 Renault: Device nValue: 0
2024-09-02 14:27:39.655 Renault: Device sValue: ''
2024-09-02 14:27:39.655 Renault: Device LastLevel: 0
2024-09-02 14:27:39.655 Renault: Device: 2 - ID: 211, Name: 'Renault - Fuel level', nValue: 0, sValue: ''
2024-09-02 14:27:39.655 Renault: Device ID: '211'
2024-09-02 14:27:39.655 Renault: Device Name: 'Renault - Fuel level'
2024-09-02 14:27:39.655 Renault: Device nValue: 0
2024-09-02 14:27:39.655 Renault: Device sValue: ''
2024-09-02 14:27:39.656 Renault: Device LastLevel: 0
2024-09-02 14:27:39.656 Renault: Device: 3 - ID: 212, Name: 'Renault - Charge', nValue: 0, sValue: ''
2024-09-02 14:27:39.656 Renault: Device ID: '212'
2024-09-02 14:27:39.656 Renault: Device Name: 'Renault - Charge'
2024-09-02 14:27:39.656 Renault: Device nValue: 0
2024-09-02 14:27:39.656 Renault: Device sValue: ''
2024-09-02 14:27:39.656 Renault: Device LastLevel: 0
2024-09-02 14:27:39.656 Renault: Device: 4 - ID: 213, Name: 'Renault - ChargeNowWhenAtHome', nValue: 0, sValue: ''
2024-09-02 14:27:39.656 Renault: Device ID: '213'
2024-09-02 14:27:39.656 Renault: Device Name: 'Renault - ChargeNowWhenAtHome'
2024-09-02 14:27:39.656 Renault: Device nValue: 0
2024-09-02 14:27:39.656 Renault: Device sValue: ''
2024-09-02 14:27:39.656 Renault: Device LastLevel: 0
2024-09-02 14:27:39.656 Renault: Device: 5 - ID: 216, Name: 'Renault - chargingStatus', nValue: 0, sValue: ''
2024-09-02 14:27:39.656 Renault: Device ID: '216'
2024-09-02 14:27:39.656 Renault: Device Name: 'Renault - chargingStatus'
2024-09-02 14:27:39.656 Renault: Device nValue: 0
2024-09-02 14:27:39.656 Renault: Device sValue: ''
2024-09-02 14:27:39.656 Renault: Device LastLevel: 0
2024-09-02 14:27:39.656 Renault: Device: 6 - ID: 209, Name: 'Renault - Distance to home', nValue: 0, sValue: ''
2024-09-02 14:27:39.656 Renault: Device ID: '209'
2024-09-02 14:27:39.656 Renault: Device Name: 'Renault - Distance to home'
2024-09-02 14:27:39.656 Renault: Device nValue: 0
2024-09-02 14:27:39.656 Renault: Device sValue: ''
2024-09-02 14:27:39.656 Renault: Device LastLevel: 0
2024-09-02 14:27:39.656 Renault: Device: 7 - ID: 214, Name: 'Renault - RefreshNow', nValue: 0, sValue: ''
2024-09-02 14:27:39.656 Renault: Device ID: '214'
2024-09-02 14:27:39.656 Renault: Device Name: 'Renault - RefreshNow'
2024-09-02 14:27:39.656 Renault: Device nValue: 0
2024-09-02 14:27:39.656 Renault: Device sValue: ''
2024-09-02 14:27:39.656 Renault: Device LastLevel: 0
2024-09-02 14:27:39.656 Renault: Device: 8 - ID: 215, Name: 'Renault - Airco/Heater', nValue: 0, sValue: ''
2024-09-02 14:27:39.656 Renault: Device ID: '215'
2024-09-02 14:27:39.656 Renault: Device Name: 'Renault - Airco/Heater'
2024-09-02 14:27:39.656 Renault: Device nValue: 0
2024-09-02 14:27:39.656 Renault: Device sValue: ''
2024-09-02 14:27:39.656 Renault: Device LastLevel: 0
2024-09-02 14:27:39.657 Renault: onStart start
2024-09-02 14:27:39.659 Renault: _connect_to_myr
2024-09-02 14:27:40.855 Status: Renault: Using accountID: 2a33e691-6a9e-4bec-8ba4-2f1cb19f40ba
2024-09-02 14:27:40.855 Renault: Succesfully logged on
2024-09-02 14:27:41.398 Status: Renault: Using VIN: VF1RHN00773229957 LicensePlate: Model: AUSTRAL HEV
2024-09-02 14:27:41.405 Renault: Engaging Vehicle
2024-09-02 14:27:41.407 Renault: _engage_vehicle NO_ACTION
2024-09-02 14:27:42.066 Living Room Air Purifier: onHeartbeat called
2024-09-02 14:27:42.679 Error: Renault: Retrieve Error: ('err.func.wired.forbidden', 'The access is forbidden')
2024-09-02 14:27:42.684 Error: Renault: Vehicle status could not be retrieved
2024-09-02 14:27:42.684 Renault: Acquiring GIL for 'onStartCallback'
2024-09-02 14:27:47.041 Renault: Pushing 'onHeartbeatCallback' on to queue
2024-09-02 14:27:47.092 Renault: Processing 'onHeartbeatCallback' message
2024-09-02 14:27:47.093 Renault: Acquiring GIL for 'onHeartbeatCallback'
2024-09-02 14:27:47.093 Renault: Calling message handler 'onHeartbeat' on 'module' type object.
2024-09-02 14:27:47.093 Renault: Acquiring GIL for 'onHeartbeatCallback'
2024-09-02 14:27:57.060 Renault: Pushing 'onHeartbeatCallback' on to queue
2024-09-02 14:27:57.110 Renault: Processing 'onHeartbeatCallback' message
2024-09-02 14:27:57.111 Renault: Acquiring GIL for 'onHeartbeatCallback'
2024-09-02 14:27:57.111 Renault: Calling message handler 'onHeartbeat' on 'module' type object.
2024-09-02 14:27:57.111 Renault: Acquiring GIL for 'onHeartbeatCallback'
2024-09-02 14:28:07.028 Renault: Pushing 'onHeartbeatCallback' on to queue
2024-09-02 14:28:07.079 Renault: Processing 'onHeartbeatCallback' message
2024-09-02 14:28:07.080 Renault: Acquiring GIL for 'onHeartbeatCallback'
2024-09-02 14:28:07.080 Renault: Calling message handler 'onHeartbeat' on 'module' type object.
```

I'll give is some try with python3.10 when I have some more time. 
Thank you for your help and don't worry at all - it seems to be something with my configuration and I don't want to lose anyones time :)

**Comment by erwinjong** [comment]
hello,

**renault-api 0.2.7** works for me as well but not the **plugin 0.28** on **Domoticz 2024.7** with **Python 3.10.12**

renault-api shows access is forbidden for **charge-mode** and **res state** but all other info is retrieveable.

error I get with the plugin is:

GetJSonDevices: exception occurred : 'stoll'
Renault EV: Retrieve Error: ('err.func.wired.forbidden', 'The access is forbidden')

check debug logging and checking url  DEBUG - Received Kamereon response 200 on GET to https://api-wired-prod-1-e                                                             uw1.wrd-aws.com/......... gives:

{"error":"missing_authorization","error_description":"**Missing API Key header**"}

It does shows some information but not all. also getting 403 response
